@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Diagrama de Contexto omnichannel parcial
LAYOUT_WITH_LEGEND()
SHOW_PERSON_PORTRAIT()

Person(cliente, "Cliente", "Cliente bemol, que utiliza os canais disponibilizados pela empresa")

Boundary(boundary, "Universo Bemol"){
    System_Ext(EmailApi, "Api de Email", "Api externa de envio de email")
    System_Ext(ViaCepApi, "Api ViaCep", "Api externa de Validação e busca de endereço")

    System(sistemaBemol, "Sistema Bemol", "Permite que o cliente realize o seu cadastro e faça compras")
}

Rel(cliente, sistemaBemol, "Realiza Cadastro, compras e visualiza produtos via")
Rel(sistemaBemol, EmailApi, "Envia Email utilizando")
Rel(EmailApi, cliente, "Envia Email para o")
Rel(sistemaBemol, ViaCepApi, "Realiza Check de CEP via")
Rel(ViaCepApi, sistemaBemol, "Retorna Dados de CEP para")

@enduml